"""Trading strategies package."""

from trade_strategies.close_momentum import CloseMomentumStrategy
from trade_strategies.protocols import Strategy, StrategyDecisionContext
from trade_strategies.registry import get_strategy, list_strategy_names
from trade_strategies.spy_opening_range_breakout import (
    SpyOpeningRangeBreakoutMidpointStopMaxOneStrategy,
    SpyOpeningRangeBreakoutTrendHoldStrategy,
    SpyOrbAtrTrail1_0Strategy,
    SpyOrbAtrTrail1_5Strategy,
    SpyOrbAtrTrail2_0Strategy,
    SpyOrbAtrTrailStrategy,
    SpyOrbBreakEvenAfter1RStrategy,
    SpyOrbStructureTrailStrategy,
)
from trade_strategies.spy_vwap_pullback import (
    DailyContextVwapReclaimStrategy,
    DynamicVwapDistanceReclaimStrategy,
    EntryFilteredTrendDayVwapReclaimStrategy,
    GapAndGoVwapPullbackStrategy,
    OpeningDriveQualityVwapReclaimStrategy,
    RvolBucketVwapReclaimStrategy,
    SpyVwapPullbackStrategy,
    SpyVwapRangeReversionOneAndHalfAtrBandStrategy,
    SpyVwapRangeReversionOneAtrBandStrategy,
    SpyVwapRangeReversionStrategy,
    SpyVwapTrendContinuationActiveRvolFilterStrategy,
    SpyVwapTrendContinuationAtrDistanceFilterStrategy,
    SpyVwapTrendContinuationBasicSignalQualityFilterStrategy,
    SpyVwapTrendContinuationDailyTrendFilterStrategy,
    SpyVwapTrendContinuationInitialStopStrategy,
    SpyVwapTrendContinuationLongShortBaseStrategy,
    SpyVwapTrendContinuationLooseRvolFilterStrategy,
    SpyVwapTrendContinuationNormalToActiveRvolFilterStrategy,
    SpyVwapTrendContinuationOneAndHalfRTargetStrategy,
    SpyVwapTrendContinuationOneRTargetStrategy,
    SpyVwapTrendContinuationOneRTargetTimeStopStrategy,
    SpyVwapTrendContinuationOpeningDriveFilterStrategy,
    SpyVwapTrendContinuationOpeningRangeConfluenceFilterStrategy,
    SpyVwapTrendContinuationOpeningRangeConfluenceLooseFilterStrategy,
    SpyVwapTrendContinuationOpeningRangeConfluenceStrictFilterStrategy,
    SpyVwapTrendContinuationSignalBreakEntryStrategy,
    SpyVwapTrendContinuationSignalQualityBreakEntryStrategy,
    SpyVwapTrendContinuationStrongSignalQualityFilterStrategy,
    SpyVwapTrendContinuationTimeStopSixBarStrategy,
    SpyVwapTrendContinuationTimeStopStrategy,
    SpyVwapTrendContinuationTimeStopThreeBarStrategy,
    SpyVwapTrendContinuationTwoRTargetStrategy,
    SymmetricSpyVwapPullbackStrategy,
    TrendDayVwapReclaimStrategy,
)

PACKAGE_NAME = "trade_strategies"

__all__ = [
    "CloseMomentumStrategy",
    "SpyOpeningRangeBreakoutMidpointStopMaxOneStrategy",
    "SpyOpeningRangeBreakoutTrendHoldStrategy",
    "SpyOrbAtrTrail1_0Strategy",
    "SpyOrbAtrTrail1_5Strategy",
    "SpyOrbAtrTrail2_0Strategy",
    "SpyOrbAtrTrailStrategy",
    "SpyOrbBreakEvenAfter1RStrategy",
    "SpyOrbStructureTrailStrategy",
    "DailyContextVwapReclaimStrategy",
    "DynamicVwapDistanceReclaimStrategy",
    "EntryFilteredTrendDayVwapReclaimStrategy",
    "GapAndGoVwapPullbackStrategy",
    "OpeningDriveQualityVwapReclaimStrategy",
    "PACKAGE_NAME",
    "RvolBucketVwapReclaimStrategy",
    "SpyVwapRangeReversionOneAndHalfAtrBandStrategy",
    "SpyVwapRangeReversionOneAtrBandStrategy",
    "SpyVwapRangeReversionStrategy",
    "SpyVwapTrendContinuationActiveRvolFilterStrategy",
    "SpyVwapTrendContinuationAtrDistanceFilterStrategy",
    "SpyVwapTrendContinuationBasicSignalQualityFilterStrategy",
    "SpyVwapTrendContinuationDailyTrendFilterStrategy",
    "SpyVwapTrendContinuationInitialStopStrategy",
    "SpyVwapTrendContinuationLooseRvolFilterStrategy",
    "SpyVwapTrendContinuationLongShortBaseStrategy",
    "SpyVwapTrendContinuationNormalToActiveRvolFilterStrategy",
    "SpyVwapTrendContinuationOneAndHalfRTargetStrategy",
    "SpyVwapTrendContinuationOneRTargetStrategy",
    "SpyVwapTrendContinuationOpeningRangeConfluenceFilterStrategy",
    "SpyVwapTrendContinuationOpeningRangeConfluenceLooseFilterStrategy",
    "SpyVwapTrendContinuationOpeningRangeConfluenceStrictFilterStrategy",
    "SpyVwapTrendContinuationOpeningDriveFilterStrategy",
    "SpyVwapTrendContinuationSignalBreakEntryStrategy",
    "SpyVwapTrendContinuationStrongSignalQualityFilterStrategy",
    "SpyVwapTrendContinuationSignalQualityBreakEntryStrategy",
    "SpyVwapTrendContinuationOneRTargetTimeStopStrategy",
    "SpyVwapTrendContinuationTimeStopSixBarStrategy",
    "SpyVwapTrendContinuationTimeStopStrategy",
    "SpyVwapTrendContinuationTimeStopThreeBarStrategy",
    "SpyVwapTrendContinuationTwoRTargetStrategy",
    "SpyVwapPullbackStrategy",
    "Strategy",
    "StrategyDecisionContext",
    "SymmetricSpyVwapPullbackStrategy",
    "TrendDayVwapReclaimStrategy",
    "get_strategy",
    "list_strategy_names",
]
